// The RFC contract, and the three consumers that must agree with it.
//
// The server's descriptors and the FMs zcl_erpl_rev_mkfm generates inside SAP
// describe the same interface. Nothing used to bind them. A mismatch is not a
// build failure and not a startup failure -- it appears as a parameter-level
// RFC error at call time, on a customer system, mid-upgrade.
//
// This file reads the ABAP generator's source and checks it against the table.
// It cannot check the SDK descriptors directly (rfc_metadata.cpp needs the NW
// RFC SDK, which this binary deliberately does not link), so rfc_metadata.cpp
// is built FROM the table instead -- one source, two readers, one checked here
// and one by construction.

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "rfc_contract.hpp"
#include "sap_setup.hpp"

using namespace erpl_rev;

namespace {

std::string ReadMkfmSource() {
    const std::string path = std::string(ERPL_REV_SOURCE_DIR) + "/abap/zcl_erpl_rev_mkfm.abap";
    std::ifstream in(path);
    REQUIRE(in.good());
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

// mkfm writes each parameter as `IV_FOO` or `EV_FOO:XSTRING` inside a
// backtick-quoted list. Pull out every such token for one FM's make( ) block.
std::vector<std::string> MkfmParamsFor(const std::string &src, const std::string &fm) {
    const auto at = src.find("name = '" + fm + "'");
    REQUIRE(at != std::string::npos);
    // The block runs until the next make( or the end of the method.
    auto end = src.find("make( out", at);
    if (end == std::string::npos) end = src.size();
    const std::string block = src.substr(at, end - at);

    std::vector<std::string> out;
    for (size_t i = 0; (i = block.find('`', i)) != std::string::npos;) {
        const auto close = block.find('`', i + 1);
        if (close == std::string::npos) break;
        out.push_back(block.substr(i + 1, close - i - 1));
        i = close + 1;
    }
    return out;
}

// The contract's spelling of one parameter, in mkfm's notation.
std::string ContractToken(const RfcParam &p) {
    const auto t = AbapTypeName(p.type);
    return t == "STRING" ? std::string(p.name) : std::string(p.name) + ":" + t;
}

}  // namespace

TEST_CASE("rfc_contract: every generated FM matches the ABAP generator", "[rfc]") {
    const auto src = ReadMkfmSource();

    for (const auto &name : GeneratedFmNames()) {
        const RfcFm *fm = FindFm(name);
        REQUIRE(fm != nullptr);

        std::vector<std::string> expected;
        for (const auto &p : fm->params) expected.push_back(ContractToken(p));

        auto actual = MkfmParamsFor(src, name);
        std::sort(expected.begin(), expected.end());
        std::sort(actual.begin(), actual.end());

        INFO("FM " << name << " drifted between rfc_contract.hpp and zcl_erpl_rev_mkfm.abap");
        CHECK(actual == expected);
    }
}

TEST_CASE("rfc_contract: doctor's name list comes from the contract", "[rfc]") {
    // There used to be a third hardcoded list here. doctor checking a set of
    // names the server does not actually register is worse than not checking.
    auto from_setup = setup::FunctionModuleNames();
    auto from_contract = GeneratedFmNames();
    std::sort(from_setup.begin(), from_setup.end());
    std::sort(from_contract.begin(), from_contract.end());
    CHECK(from_setup == from_contract);
}

TEST_CASE("rfc_contract: STFC_CONNECTION is not generated", "[rfc]") {
    // SAP ships it. Generating it would fail, and asking doctor to verify it as
    // one of ours would report a missing object that is not missing.
    const auto gen = GeneratedFmNames();
    CHECK(std::find(gen.begin(), gen.end(), "STFC_CONNECTION") == gen.end());
    CHECK(FindFm("STFC_CONNECTION") != nullptr);
}

TEST_CASE("rfc_contract: every import is optional", "[rfc]") {
    // The rule that makes an interface change survivable: a caller generated by
    // an older mkfm, meeting a newer server, must still bind. Any parameter
    // added from here on is optional for the same reason.
    for (const auto &fm : RfcContract())
        for (const auto &p : fm.params)
            if (p.dir == RfcDir::Import) {
                INFO(fm.name << "." << p.name << " is a non-optional import");
                CHECK(p.optional);
            }
}

TEST_CASE("rfc_contract: every FM reports errors the same way", "[rfc]") {
    // EV_ERROR is how a handler returns a failure instead of throwing across
    // the RFC boundary. An FM without it has no way to say what went wrong.
    for (const auto &fm : RfcContract()) {
        if (std::string(fm.name).rfind("Z_DUCKDB_", 0) != 0) continue;
        bool has = false;
        for (const auto &p : fm.params)
            if (std::string(p.name) == "EV_ERROR" && p.dir == RfcDir::Export) has = true;
        INFO(fm.name << " has no EV_ERROR export");
        CHECK(has);
    }
}
