#include "rfc_contract.hpp"

namespace erpl_rev {

namespace {
constexpr auto S = RfcParamType::String;
constexpr auto X = RfcParamType::XString;
constexpr auto C = RfcParamType::Char;
constexpr auto In = RfcDir::Import;
constexpr auto Out = RfcDir::Export;

// Imports are optional throughout: mkfm marks every RSIMP entry optional, and
// keeping the descriptor in step means an older ABAP caller that does not know
// a newly added parameter still works against a newer server. Every parameter
// added from here on MUST be optional for that reason.
RfcParam Imp(const char *n, RfcParamType t = S) { return {n, t, In, 0, 0, true}; }
RfcParam Exp(const char *n, RfcParamType t = S) { return {n, t, Out, 0, 0, false}; }
}  // namespace

const std::vector<RfcFm> &RfcContract() {
    static const std::vector<RfcFm> kContract = {
        // SAP's own connection test; not generated by mkfm.
        {"STFC_CONNECTION",
         {{"REQUTEXT", C, In, 255, 510, true},
          {"ECHOTEXT", C, Out, 255, 510, false},
          {"RESPTEXT", C, Out, 255, 510, false}}},

        {"Z_DUCKDB_QUERY",
         {Imp("IV_SQL"), Exp("EV_COLUMNS"), Exp("EV_ROWS"), Exp("EV_ROW_COUNT"),
          Exp("EV_ERROR")}},

        {"Z_DUCKDB_INGEST",
         {Imp("IV_TARGET"), Imp("IV_MODE"), Imp("IV_KEYS"), Imp("IV_PARQUET_OUT"),
          Imp("IV_INIT_SQL"), Imp("IV_DDL"), Imp("IV_DATA"), Imp("IV_XDATA", X),
          Imp("IV_OP_COL"), Exp("EV_ROWS_AFFECTED"), Exp("EV_ERROR")}},

        {"Z_DUCKDB_SNAPSHOT_MERGE",
         {Imp("IV_TARGET"), Imp("IV_STAGING"), Imp("IV_KEYS"), Exp("EV_INS"), Exp("EV_UPD"),
          Exp("EV_DEL"), Exp("EV_ERROR")}},

        {"Z_DUCKDB_CDC_PLAN",
         {Imp("IV_TARGET"), Imp("IV_SOURCE"), Imp("IV_KEYS"), Imp("IV_MODE"),
          Imp("IV_PLATFORM"), Imp("IV_ACTION"), Exp("EV_PLAN"), Exp("EV_ERROR")}},

        {"Z_DUCKDB_CDC_APPLY",
         {Imp("IV_TARGET"), Imp("IV_STAGING"), Imp("IV_KEYS"), Exp("EV_INS"), Exp("EV_UPD"),
          Exp("EV_DEL"), Exp("EV_PRUNE"), Exp("EV_APPLIED"), Exp("EV_ERROR")}},

        {"Z_DUCKDB_OPEN",
         {Imp("IV_SQL"), Exp("EV_HANDLE"), Exp("EV_COLUMNS"), Exp("EV_ERROR")}},

        {"Z_DUCKDB_FETCH",
         {Imp("IV_HANDLE"), Imp("IV_PAGE_ROWS"), Exp("EV_XDATA", X), Exp("EV_FETCHED"),
          Exp("EV_DONE"), Exp("EV_ERROR")}},

        {"Z_DUCKDB_CLOSE", {Imp("IV_HANDLE"), Exp("EV_ERROR")}},
    };
    return kContract;
}

std::vector<std::string> GeneratedFmNames() {
    std::vector<std::string> out;
    for (const auto &fm : RfcContract())
        if (std::string(fm.name).rfind("Z_DUCKDB_", 0) == 0) out.emplace_back(fm.name);
    return out;
}

const RfcFm *FindFm(const std::string &name) {
    for (const auto &fm : RfcContract())
        if (name == fm.name) return &fm;
    return nullptr;
}

std::string AbapTypeName(RfcParamType t) {
    switch (t) {
        case RfcParamType::String: return "STRING";
        case RfcParamType::XString: return "XSTRING";
        case RfcParamType::Char: return "CHAR";
    }
    return "STRING";
}

}  // namespace erpl_rev
