// Byte-compatible codec for SAP's binary sXML ("BXML"), the asXML document shape
// that `CALL TRANSFORMATION id` produces/consumes in ABAP (verified against the
// ABAP kernel — see test/fixtures/bxml_fixtures.txt, generated by
// abap/zcl_erpl_rev_fix.abap).
//
// This lets the C++ RFC server exchange tabular data with ABAP using only the
// STANDARD slim ABAP idiom on the other side:
//   serialize:   w = cl_sxml_string_writer=>create( type = if_sxml=>co_xt_binary ).
//                CALL TRANSFORMATION id SOURCE data = <itab> RESULT XML w.
//   deserialize: r = cl_sxml_string_reader=>create( input = x ).
//                CALL TRANSFORMATION id SOURCE XML r RESULT data = <itab>.
//
// Document model (asXML): a table serializes to
//   <asx:abap version="1.0" xmlns:asx="..."><asx:values>
//     <NODE><item><COL1>v</COL1><COL2>v</COL2></item>...</NODE>
//   </asx:values></asx:abap>
// where NODE = the CALL TRANSFORMATION parameter name (we fix it to "DATA"),
// rows are <item>, columns are child elements by name. NULL/empty string is an
// empty element (no text). All text content is raw UTF-8 (NOT XML-escaped) with
// byte lengths.
//
// The binary token grammar (reverse-engineered, byte-exact):
//   magic "BXML"; PI  3F <len> <name> <len> <val>  (VER 0.7, ENC utf-8);
//   EncodeItem 2B <len1> <name>  — interns <name>, assigns the next auto id;
//   TagStart   3C <id6> <flag>   — opens an element by interned id (id6 = 6-bit
//                                  varint: 1 byte if <128, else 2 bytes);
//   attributes 3A.. / 40.. (skipped on read; only the constant header uses them);
//   Text       54 (<len1><raw bytes>)+   terminated by the following TagEnd;
//   Binary     42 (<len1><raw bytes>)+   (xstring columns);
//   TagEnd     3E.
#pragma once

#include <string>
#include <string_view>
#include <functional>
#include <vector>

namespace erpl_rev {
namespace sxml {

// One decoded table: column names in order + rows of optional cell strings
// (nullopt == empty element / NULL). Values are raw UTF-8.
struct Table {
    std::vector<std::string> columns;
    // rows[r] has one entry per column, in `columns` order; empty string for an
    // empty element. (We model "present but empty" as ""; asXML doesn't
    // distinguish NULL from empty for our scalar use.)
    std::vector<std::vector<std::string>> rows;
};

// Decode a binary-sXML (BXML) asXML document into a Table. `bytes` is the raw
// xstring as produced by CL_SXML_STRING_WRITER(co_xt_binary). Throws
// std::runtime_error on malformed input. Column set is taken from the first
// <item>; later items map by element name.
Table Decode(const std::string &bytes);

// Decode without building a Table.
//
// `on_columns` is called once, when the first row's column names are known;
// `on_row` once per row with that row's cells as views INTO `bytes`. The views
// are valid for the duration of the call only -- copy anything kept.
//
// This exists because materialising the table is the expensive part, not the
// parsing: a 50k-row package of a 420-column table is 21 million std::string
// allocations and roughly half a gigabyte of resident memory, for data that a
// consumer immediately copies elsewhere and drops. Streaming it costs neither.
void DecodeStreaming(const std::string &bytes,
                     const std::function<void(const std::vector<std::string> &)> &on_columns,
                     const std::function<void(const std::vector<std::string_view> &)> &on_row);

// Encode a Table into byte-exact BXML matching what the ABAP kernel emits for
// `CALL TRANSFORMATION id SOURCE <node> = <itab>`. `node` is the root element
// name (e.g. "DATA"). Column names should be valid ABAP component names
// (uppercase). Produces output that CL_SXML_STRING_READER + CALL TRANSFORMATION
// id deserializes back into the itab.
std::string Encode(const std::string &node, const Table &table);

// Row-streaming encoder: emits the SAME bytes as Encode() but without first
// materializing a Table (no intermediate vector<vector<string>>). The caller
// feeds rows cell-by-cell straight from its source (e.g. DuckDB chunks), so the
// hot cursor path avoids one full string-matrix copy per page.
//
// Usage (mirrors Encode's token order exactly):
//   StreamEncoder e(columns);          // columns in order
//   for each row:  e.StartRow();
//                  for c in 0..ncol:  e.Cell(c, ptr, len);   // len==0 => empty
//                  e.EndRow();
//   std::string bxml = e.Finish();
// Cell() must be called for every column index 0..ncol-1 in order within a row.
// `ptr` need only stay valid for the duration of the Cell() call (bytes are
// copied immediately). A NULL/empty value is Cell(c, nullptr, 0).
class StreamEncoder {
public:
    explicit StreamEncoder(std::vector<std::string> columns);
    void StartRow();
    void Cell(size_t col, const char *bytes, size_t len);
    void EndRow();
    std::string Finish();                       // closes the doc; moves out the buffer
    long long row_count() const { return rows_; }

private:
    std::vector<std::string> cols_;
    std::string out_;
    long long rows_ = 0;     // completed rows; PutName interning happens on row 0 only
    bool in_first_ = false;  // true while building the very first row
};

} // namespace sxml
} // namespace erpl_rev
