# Bake the production ABAP sources into the binary.
#
# `uvx erpl-rev setup` has no checkout to read from, so the objects it deploys
# have to travel inside the executable. Raw string literals keep the generated
# file readable and the build fast; ABAP source contains no `)ERPLABAP"`
# sequence, and the guard below fails the build loudly rather than silently
# emitting something that will not compile.
#
# The list is the PRODUCTION set in DEPENDENCY order — see src/abap_assets.hpp
# for why the order is what it is. Test drivers, demo reports and the ZWIDE_BSEG
# fixture are deliberately absent: they belong in a dev checkout, not a
# customer's system.

set(ERPL_ABAP_ASSETS
    # file | ABAP name | ADT type | source --type | description
    "zdelta_wm.ddl|ZDELTA_WM|TABL/DT|TABL|erpl-rev delta watermark table"
    "zif_erpl_rev_progress.intf.abap|ZIF_ERPL_REV_PROGRESS|INTF/OI|INTF|replicate progress callback"
    "zcl_erpl_rev_typemap.abap|ZCL_ERPL_REV_TYPEMAP|CLAS/OC||DDIC<->DuckDB type map"
    "zcl_erpl_rev_util.abap|ZCL_ERPL_REV_UTIL|CLAS/OC||query/describe/replicate"
    "zcl_erpl_rev_delta.abap|ZCL_ERPL_REV_DELTA|CLAS/OC||delta engine"
    "zcl_erpl_rev_deltadrv.abap|ZCL_ERPL_REV_DELTADRV|CLAS/OC||delta change-injection driver"
    "zcl_erpl_rev_cdc.abap|ZCL_ERPL_REV_CDC|CLAS/OC||trigger-CDC executor"
    "zcl_erpl_rev_mkfm.abap|ZCL_ERPL_REV_MKFM|CLAS/OC||create the Z_DUCKDB_* RFC FMs"
    "zcl_erpl_rev_setup.abap|ZCL_ERPL_REV_SETUP|CLAS/OC||create the registered destination"
    "zcl_erpl_rev_diag.abap|ZCL_ERPL_REV_DIAG|CLAS/OC||round-trip probe (STFC_CONNECTION)"
    "z_erpl_rev_repl_worker.prog.abap|Z_ERPL_REV_REPL_WORKER|PROG/P||parallel-replication worker"
    "z_erpl_rev_replicate.prog.abap|Z_ERPL_REV_REPLICATE|PROG/P||replicate SAP table -> DuckDB"
    "z_erpl_rev_sql.prog.abap|Z_ERPL_REV_SQL|PROG/P||DuckDB SQL console"
    "z_erpl_rev_delta.prog.abap|Z_ERPL_REV_DELTA|PROG/P||delta orchestration loop"
)

function(erpl_generate_abap_assets OUT_VAR)
    set(_gen "${CMAKE_BINARY_DIR}/generated/abap_assets.cpp")
    set(_body "// GENERATED by cmake/embed_abap.cmake -- do not edit.\n")
    string(APPEND _body "#include \"abap_assets.hpp\"\n\nnamespace erpl_rev::abap {\nnamespace {\n\n")

    set(_entries "")
    set(_idx 0)
    foreach(_spec IN LISTS ERPL_ABAP_ASSETS)
        string(REPLACE "|" ";" _parts "${_spec}")
        list(GET _parts 0 _file)
        list(GET _parts 1 _name)
        list(GET _parts 2 _adt)
        list(GET _parts 3 _srct)
        list(GET _parts 4 _desc)

        set(_path "${CMAKE_CURRENT_SOURCE_DIR}/abap/${_file}")
        if(NOT EXISTS "${_path}")
            message(FATAL_ERROR
                "embed_abap: ${_path} is missing. The asset list in "
                "cmake/embed_abap.cmake is out of step with abap/ -- fix one or the other; "
                "shipping a binary whose setup silently omits an object is worse than not building.")
        endif()
        file(READ "${_path}" _text)
        if(_text MATCHES "\\)ERPLABAP\"")
            message(FATAL_ERROR
                "embed_abap: ${_file} contains the raw-string delimiter )ERPLABAP\" -- "
                "pick a different delimiter in cmake/embed_abap.cmake.")
        endif()
        string(APPEND _body "constexpr std::string_view kSrc${_idx} = R\"ERPLABAP(${_text})ERPLABAP\";\n\n")
        string(APPEND _entries "    {\"${_file}\", \"${_name}\", \"${_adt}\", \"${_srct}\", \"${_desc}\", kSrc${_idx}},\n")
        math(EXPR _idx "${_idx} + 1")
    endforeach()

    string(APPEND _body "} // namespace\n\n")
    string(APPEND _body "const std::vector<Asset> &ProductionAssets() {\n")
    string(APPEND _body "    static const std::vector<Asset> kAssets = {\n${_entries}    };\n")
    string(APPEND _body "    return kAssets;\n}\n\n")
    string(APPEND _body "const Asset *Find(std::string_view name) {\n")
    string(APPEND _body "    for (const auto &a : ProductionAssets()) if (a.name == name) return &a;\n")
    string(APPEND _body "    return nullptr;\n}\n\n")
    string(APPEND _body "} // namespace erpl_rev::abap\n")

    file(GENERATE OUTPUT "${_gen}" CONTENT "${_body}")
    set(${OUT_VAR} "${_gen}" PARENT_SCOPE)
    message(STATUS "erpl-rev: embedding ${_idx} ABAP objects for `erpl-rev setup`")
endfunction()
